### ISSUE TITLE
Explanaiton of evaluation not fully visible

### ISSUE THREAD

**Issue by jbracher** [epiforecasts/covid19-forecast-hub-europe-website#9]
When selecting Germany the explanatory text on the different evaluation methods is partly covered by the results table (likely due to the larger number of models for Germany).

Observed in Firefox on Ubuntu.

**Comment by Bisaloo** [comment]
Should be fixed by https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/577. Please let me know if you are still encountering issues with this.

**Comment by Bisaloo** [comment]
(this will take effect in the next round of reports since reports for this week were created before this got merged)
